# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

APP_ID = ENV['FIREBASE_ANDROID_APPID']
FIREBASE_TOKEN = ENV['FIREBASE_CI_TOKEN']
BUILD_NUMBER = ENV['BUILD_NUMBER']

platform :android do
  desc "Deploy a new beta"
  lane :distribute_beta do
    firebase_app_distribution(
      app: APP_ID,
      groups: "testers",
      release_notes: BUILD_NUMBER,
      firebase_cli_path: "/usr/local/bin/firebase",
      firebase_cli_token: FIREBASE_TOKEN,
      apk_path: "../build/app/outputs/flutter-apk/app-staging-release.apk",
      service_credentials_file: "firebase_credentials.json"
    )
  end
end