# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "develop","master","staging" ]
  pull_request:
    branches: [ "develop", "staging" ]
jobs:
  verify-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2.6.1
      with:
        flutter-version: '3.3.0'
        channel: 'stable'
    - run: flutter pub get
    - run: dart analyze
    - run: flutter test

